### ISSUE TITLE
PowerUp should show up in the UI and disappears from UI when used

### ISSUE THREAD

**Issue by tarstarkes** [EOUCS344Sp15/ReleaseTheKraken#10]
Implement functionality for adding the PowerUp to the UI as well as functionality for making it despawn when the user activates the PowerUp. I would suggest using the dispose() call to destroy the entity, and then decriment the UI's power up counter for that particular type of PowerUp

**Comment by Dalton-Baird** [comment]
I just got this to work, using a different system that uses only an array of integers to represent the amount of every type of power up.  Clicking a power up button while there are 1 or more power ups of that type will call EntityPowerUp.onUse(), which eventually will apply the power up's effects.
