### ISSUE TITLE
Sidebar - button customization and extension

### ISSUE THREAD

**Issue by montchm** [EOUCS344Sp15/ReleaseTheKraken#20]
@EOUCS344Sp15/teamb 

Create a class that extends the buttons already in place in the sidebar for units and PowerUps.

PowerUps should be able to draw the number of powerUPs available on the button.

**Comment by Dalton-Baird** [comment]
Just finished this.  Everything works, except the unit buttons don't spawn the units.  We don't have a path to spawn them on yet.
