### ISSUE TITLE
Adjust player character functionality

### ISSUE THREAD

**Issue by DJ-Flores** [EOUCS344Sp15/ReleaseTheKraken#27]
Make sure it doesn't collide with other objects(i.e. towers), and if it does, not allow it to go over them. I believe we could skip the whole collision detection with towers and the player character if we get the map set up correctly since this is a reverse tower defense and there is usual a defined path. Unless we aren't doing defined paths.

**Comment by Dalton-Baird** [comment]
I think this was all implemented when we set up Box2D physics.  Closing...
