### ISSUE TITLE
Using WASD and the arrow keys at the same time allows the player to accelerate twice as fast

### ISSUE THREAD

**Issue by Dalton-Baird** [EOUCS344Sp15/ReleaseTheKraken#30]
When using both the WASD and the arrow keys at the same time, for example, by pressing a and left, the player will accelerate twice as fast, due to two key events happening during the same tick.  This can either be left as is, since the player reaches max speed so quickly anyways, or boolean variables can keep track of if the button has already been pressed this tick.  A more general solution might be required, as this could potentially effect other things as well, if they have multiple key binds.

**Comment by Dalton-Baird** [comment]
This has become even more of an issue now that we have Box2D.  You can now accelerate twice as fast, and reach a speed that is twice as fast!

**Comment by tarstarkes** [comment]
added a boolean variable for each directional, the boolean is reset on update to false for each directional :smile:
