### ISSUE TITLE
How should collision be implemented?

### ISSUE THREAD

**Issue by Dalton-Baird** [EOUCS344Sp15/ReleaseTheKraken#33]
I was having difficulty implementing a rectangular hitbox based collision system.  The best I could get for collision detection was having every entity that has a hitbox checking for collisions with every other entity with a hitbox, which is O(n^2), which seems like a lot, but it might not be.  I also had issues trying to get entities that collide to not overlap, and be able to move away from each other.  What I did was in onUpdate(), I added the entity's velocity to its position, and then checked, for all other entities, if that caused a collision.  If it did, I reversed the velocity and added it to the position to move it back.  Currently, this is resulting in the entities getting stuck together.  Multiplying the velocity by 1.1 results in them getting pulled together when colliding, and multiplying by 1.2 results in them flying apart at high speed (which is pretty funny).  

After that, I started thinking if it might be better to use Box2D instead, but that is kind of overkill for what we want to do in this game.  It would allow for some more features though, such as cannon balls transferring force to obstacles to push them, projectiles "bouncing off" a squishy jelly fish, rotation, rotational inertia, and more.  Obstacles could be "pushed" out of the way with excessive force, which would probably be funner than just attacking them.  The kraken could "grab" stuff (with Box2D joints), and fling them around.  Box2D would allow for better physics without the need to write any collision detection code, and it runs in native C++ code, which is faster than Java.  The downside is that due to the way it is set up, it would require a large refactor of how everything works.  This refactor would mostly effect world entity storage, entity interaction, and entity spawning.  Box2D would also make dealing with physics more difficult, due to the more advanced physics simulation.  Instead of just defining a rectangular hitbox, position, and velocity, you would have to define a simple or detailed collection of shapes to represent the hitbox, and set the mass, friction, restitution, position, velocity, and angular velocity.  Most of those can also be defined for each shape that makes up a hitbox.  
#### So what do you guys think?

Should we use Box2D (already made), with more advanced, harder to set up physics, or make our own system (not made yet) with simpler, easier to set up physics?

The Box2D libraries are already included in the project just in case we wanted to use it.

**Comment by Phigz** [comment]
I used Box2D in my app and I think using it would be a benefit more than a nuisance. I'm for it.

**Comment by Dalton-Baird** [comment]
Yeah, I used it in my app too, and I kind of want to use it in this game.  I just wanted to see what everybody else thinks.  If we use Box2D, it is something that you would want to get started on as soon as possible.

**Comment by Dalton-Baird** [comment]
It was decided in class that we are going to use Box2D.
