### ISSUE TITLE
Add the pause screen

### ISSUE THREAD

**Issue by Dalton-Baird** [EOUCS344Sp15/ReleaseTheKraken#37]
This depends on issue #36 to be finished first.  A pause screen needs to be added that allows the user to resume the game, quit, or maybe change settings.  The pause screen can render on top of a screenshot taken of the game screen.

**Comment by Dalton-Baird** [comment]
Well, you can now switch screens, so we should be able to start working on this now.  This pause screen can take a Pixmap in its constructor that it will use to render the screenshot background.  The pause button can take the screenshot when pressed, and then push a new pause screen with the pixmap.  @LucasSchuetz, @montchm If any of you want to work on this, feel free to do it.  Make sure you assign yourself to the issue though.

**Comment by montchm** [comment]
Thanks Dalton. I will look in to this more tomorrow morning.

**Comment by Phigz** [comment]
The screen has been created and is working. The background is black and Dalton and I were having trouble displaying a Pixmap to the background. Leaving the issue open until that is resolved.

**Comment by Dalton-Baird** [comment]
The pixmap is now displayed, but I feel like it might be a good idea to alter it a little bit, to differentiate the background from the actual pause menu.  We could make it darker, or blur it or something.  That would have to be done by manipulating the pixels directly though.  A GLSL shader could also be used, but I don't know how to write one.

**Comment by Dalton-Baird** [comment]
I actually got GLSL shaders to work. I "copy and pasted" the default one and changed it a bit to make it render stuff grayscale and darker.  So far, it is only enabled when drawing the background on the pause screen!  The pause screen is pretty much complete now :smile:
