### ISSUE TITLE
Application Freezes after sitting idle

### ISSUE THREAD

**Issue by micahjade** [EOUCS344Sp15/ReleaseTheKraken#57]
Seems idle time causes the game to freeze up

**Comment by Dalton-Baird** [comment]
I'm pretty sure this is related to issue #53...  It might not be so rare anymore.

**Comment by Dalton-Baird** [comment]
Since this is almost exactly the same as the other issue, and we don't have any way of knowing if they are two different types of crashes, I'm closing this issue.  Go look at the other one now.
