### ISSUE TITLE
EntityFish projectile problem

### ISSUE THREAD

**Issue by sayerbartlett** [EOUCS344Sp15/ReleaseTheKraken#64]
EntityFish attack gets the correct target coordinates, but the projectile does Not go toward them.

**Comment by Dalton-Baird** [comment]
Fixed.  The projectile constructor takes the projectile's velocity, not the coordinates it should fire at.  You have to calculate the velocity manually.  It isn't very hard with vectors though, go check it out!  I also made EntityWaterSquirt render correctly, with the correct texture.

Oh, and you might want to go tweak the projectile firing force.  Right now, it's set to 100 newtons.
