### ISSUE TITLE
Display Countdown for duration of power ups

### ISSUE THREAD

**Issue by DJ-Flores** [EOUCS344Sp15/ReleaseTheKraken#82]
Implement a countdown to show how much time you have left on a certain power up.

**Comment by Phigz** [comment]
I was thinking that when the power up is used (this would be used on all power ups but the heal), grey it out and have the timer proceed by filling the circle with the original, clickable color. This would also allow for the power ups to avoid stacking (if we did want them not to stack).

**Comment by DJ-Flores** [comment]
I have a very basic set up of one on my computer at home. Ill try and push it later.

**Comment by Phigz** [comment]
I was just talking to Dalton about this and he reminded me the power ups have a radius and he was thinking that having the power up duration as a bar under (or above) each creatures health bar.

**Comment by DJ-Flores** [comment]
Yeah that's what I have.

**Comment by Dalton-Baird** [comment]
The bar's color could also match the power up's icon color to allow you to tell which power up is currently active.  This would be nice.
