### ISSUE TITLE
Krakens get stuck on terrain fairly easily

### ISSUE THREAD

**Issue by micahjade** [EOUCS344Sp15/ReleaseTheKraken#84]
Yeah kraken doesn't even make it to the pirate ship most the time (or ever).

**Comment by Dalton-Baird** [comment]
Yeah... I'm still working on it.  This will get fixed when we enhance targeting to be ranged, and not target stuff behind walls.  It usually gets stuck because the tentacles want to go somewhere else, while the body wants to follow the path.

**Comment by Dalton-Baird** [comment]
Well, I just enhanced the kraken's hitbox, and made it so it doesn't try to target stuff behind walls now.  It's a little better, but still not done.

**Comment by Dalton-Baird** [comment]
I just enhanced the Kraken's targeting system.  Now, the body will help it move towards its target, or the path if there are no targets.  Every time I tested it, it easily got to the pirate base, demolishing everything in its way.  It has a little trouble with the sharp corner, but it never got stuck.  I think it's fixed enough to close this issue.
