### ISSUE TITLE
Projectile collision

### ISSUE THREAD

**Issue by DJ-Flores** [EOUCS344Sp15/ReleaseTheKraken#90]
Is it possible to make the projectiles disappear on collision? The screen gets pretty clustered with enemy projectiles and player unit projectiles.

**Comment by Dalton-Baird** [comment]
I'm pretty sure an issue for this already exists.  Issue #78.  I kind of like it how it is, but there was one thing I wanted to set up eventually, and that was projectiles despawning when moving too slow.  This might result in fewer projectiles on the screen.  Alternately, we can set up some configuration settings that lets you customize stuff like this in the settings screen.

**Comment by Dalton-Baird** [comment]
Well, I just added the minimum projectile velocity thing.  The minimum velocities of the projectiles might need tweaking.  Projectiles can still collide, but if two projectiles of similar mass (such as a water squirt and a cannon ball) collide directly, they will cancel each other's velocity out and result in both despawning.  If they just brush each other, they will still bounce.  The player's projectiles are heavy and fast, and usually reverse a hit projectile's velocity.  Go check it out.

**Comment by DJ-Flores** [comment]
Yeah I just meant when it hits the coral. Looks like you fixed what I was talking about.
